FROM alpine:latest
RUN wget https://wordpress.org/latest.tar.gz

FROM ubuntu:xenial
COPY --from=0 /latest.tar.gz /tmp/
RUN tar -xvzf /tmp/latest.tar.gz --strip-components=1 -C /var/www/html
CMD ["apachectl", "-D", "FOREGROUND"]
