version: "3"
services:
  wordpress:
    build:
      context: ./wordpress/
      dockerfile: Dockerfile.wordpress
    image: colinbarnabas/wordpress
    volumes:
      - wp-content:/var/www/html/wp-content/
    env_file: ./wordpress/env_wordpress
    ports:
      - "80:80"
    depends_on:
      - mariadb
      - nginx

  mariadb:
    build:
      context: ./mariadb/
      dockerfile: Dockerfile.mariadb
    image: colinbarnabas/mariadb
    volumes: 
      - wp-db:/var/lib/mysql/

    env_file: ./mariadb/env_mariadb

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.nginx
    image: colinbarnabas/nginx

volumes:
  wp-db:
  wp-content:
