version: "3"
services:
  wordpress:
    build:
      context: ./wordpress/
      dockerfile: Dockerfile.wordpress
    image: colinbarnabas/wordpress
    volumes:
      - wp-content:/var/www/html/wp-content/
    env_file: ./wordpress/env_wordpress
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql:mysql


  mysql:
    build:
      context: ./mysql/
      dockerfile: Dockerfile.mysql
    image: colinbarnabas/mysql
    volumes: 
      - wp-db:/var/lib/mysql/
      - ./mysql-logs:/var/log/mysql/

    env_file: ./mysql/env_mysql

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.nginx
    image: colinbarnabas/nginx
    links:
      - wordpress:wordpress

volumes:
  wp-db:
  wp-content:
