version: "3"
services:
  wordpress:
    build:
      context: ./wordpress/
      dockerfile: Dockerfile.wordpress
    image: colinbarnabas/wordpress
    volumes:
      - wp-content:/var/www/html/wp-content/
    env_file: ./wordpress/env_wordpress
    networks:
      local:
        aliases:
          - wp
      
    expose:
      - "80"
    depends_on:
      - mysql
    restart: always

  mysql:
    build:
      context: ./mysql/
      dockerfile: Dockerfile.mysql
    image: colinbarnabas/mysql
    expose: 
      - "3306"
    networks:
      local:
        aliases:
          - db
    volumes: 
      - wp-db:/var/lib/mysql/
      - ./mysql-logs:/var/log/mysql/

    env_file: ./mysql/env_mysql
    restart: always

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.nginx
    image: colinbarnabas/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local 
    #restart: always

volumes:
  wp-db:
  wp-content:

networks:
  local:
