FROM ubuntu:xenial
RUN set -ex \
        && apt-get -q update \
        && apt-get -yq --no-install-recommends install mysql-server \
        && rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh /
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mysqld"]
