CREATE DATABASE IF NOT EXISTS "${MYSQL_DATABASE}";
CREATE USER IF NOT EXISTS "${MYSQL_USER}"@"%";
SET PASSWORD FOR "${MYSQL_USER}"@'%' = PASSWORD("${MYSQL_PASSWORD}");
GRANT ALL ON "${MYSQL_DATABASE}"* TO "${MSQL_USER}"@"%";
FLUSH PRIVILEGES;
SHOW DATABASES;
